$(document).ready(function() {
	var aLangKeys=new Array();
	aLangKeys['en']=new Array();
	aLangKeys['es']=new Array();

	//English
	aLangKeys['en']['home']='Home';
	aLangKeys['en']['aboutUs']='About Us';
	aLangKeys['en']['team']='Team';
	aLangKeys['en']['services']='Services';
	aLangKeys['en']['portfolio']='Portfolio';
	aLangKeys['en']['contactUs']='Contact Us';	
	aLangKeys['en']['aboutus1']='We are ';	
	aLangKeys['en']['aboutus2']='FanLabs';	
	aLangKeys['en']['aboutus3']='We are a close team of ';	
	aLangKeys['en']['aboutus4']='creatives, designers & developers ';	
	aLangKeys['en']['aboutus5']='who work together to create beautiful, engaging digital experiences. We enjoy finding solutions to  ';	
	aLangKeys['en']['aboutus6']='your problems.';	
	aLangKeys['en']['aboutus7']='What do ';	
	aLangKeys['en']['aboutus8']='we';	
	aLangKeys['en']['aboutus9']='actually do?';	
	aLangKeys['en']['aboutus10']='Web Design';
	aLangKeys['en']['aboutus11']='Programming';
	aLangKeys['en']['aboutus12']='UI / UX';
	aLangKeys['en']['aboutus13']='Fun';
	aLangKeys['en']['aboutus14']='Our ';
	aLangKeys['en']['aboutus15']='Strategy';
	aLangKeys['en']['aboutus16']='Responsibility';	
	aLangKeys['en']['aboutus17']='We only work with very responsible developers, who will give the most of them to achieve the best results possible.';
	aLangKeys['en']['aboutus18']='Team Working';
	aLangKeys['en']['aboutus19']='We have co-located teams that will work together in your project. Communication is one of the keys of success in Agile projects, so we need highly comunnicated teams, with very good soft skills.';
	aLangKeys['en']['aboutus20']='Innovation';
	aLangKeys['en']['aboutus21']='We know that each application can be improved. We work with you not only to develop your application, but to give some ideas about how your application could be better. We want your success, because that is our success.';
	aLangKeys['en']['aboutus22']='FanLabs ';
	aLangKeys['en']['aboutus23']='in numbers';
	aLangKeys['en']['aboutus24']='Cups of Coffee';
	aLangKeys['en']['aboutus25']='Thermo of Mate';
	aLangKeys['en']['aboutus26']='Beers';
	aLangKeys['en']['aboutus27']='Chess Game';
	aLangKeys['en']['serviceTitle1']='Development';
	aLangKeys['en']['serviceTitle2']='Web Application';
	aLangKeys['en']['serviceTitle3']='Responsive Design';
	aLangKeys['en']['serviceTitle4']='Clean Code';
	aLangKeys['en']['serviceTitle5']='Personalize';
	aLangKeys['en']['serviceTitle6']='Creative Idea';
	aLangKeys['en']['service1']='We are a strong and experienced team, capable of developing any application using most advanced technologies.';
	aLangKeys['en']['service2']='We design and develop custom web applications that deliver the experience our customers want.';
	aLangKeys['en']['service3']='We use responsive web design techniques to build a single website that adapts to multiple screen resolutions.';
	aLangKeys['en']['service4']='We work looking for the highest quality and performance in all our developments.';
	aLangKeys['en']['service5']='We will work with you to explore new ideas, lovingly designed products & services and delightful user experiences.';
	aLangKeys['en']['service6']='We work with you not only to develop your application, but to give some ideas about how your application could be better.';
	aLangKeys['en']['service7']='Our ';
	aLangKeys['en']['service8']='Services';	
	aLangKeys['en']['service9']='At FanLabs we want to offer widest and the ';
	aLangKeys['en']['service10']='most efficient services';
	aLangKeys['en']['service11']=' to your company.';
	aLangKeys['en']['service12']='Send us your email and we will ';
	aLangKeys['en']['service13']='contact you.';
	aLangKeys['en']['service14']='Join Us!';
	aLangKeys['en']['service15']='Send';
	aLangKeys['en']['contactus1']='Go on,';
	aLangKeys['en']['contactus2']=' contact us!';
	aLangKeys['en']['contactus3']='Read More';
	aLangKeys['en']['team1']='Our ';
	aLangKeys['en']['team2']='Team';
	aLangKeys['en']['team3']='We are a ';
	aLangKeys['en']['team4']='team';
	aLangKeys['en']['team5']=' that ';
	aLangKeys['en']['team6']='love';
	aLangKeys['en']['team7']=' what we do!. We have different skills and we merge this skills to ';
	aLangKeys['en']['team8']='create';
	aLangKeys['en']['team9']=' a software ';
	aLangKeys['en']['team10']='robust, dynamic and friendly.';
	aLangKeys['en']['team11']='We ';
	aLangKeys['en']['team12']='are the ';
	aLangKeys['en']['team13']='team';
	aLangKeys['en']['team14']='Full Profile';
	aLangKeys['en']['team15']='Co-Founder & Developer';
	

	//Spanish
	aLangKeys['es']['home']='Principal';
	aLangKeys['es']['aboutUs']='Sobre nosotros';
	aLangKeys['es']['team']='Nosotros';
	aLangKeys['es']['services']='Servicios';
	aLangKeys['es']['portfolio']='Portfolio';
	aLangKeys['es']['contactUs']='Contacto';


	aLangKeys['es']['aboutus1']='Nosotros somos ';	
	aLangKeys['es']['aboutus2']='FanLabs';	
	aLangKeys['es']['aboutus3']='Somos un equipo de ';	
	aLangKeys['es']['aboutus4']='creativos, diseñadores y programadores ';	
	aLangKeys['es']['aboutus5']='que trabajamos juntos para crear un hermosa solución. Nosotros disfrutamos encontrar soluciones para ';	
	aLangKeys['es']['aboutus6']='tus problemas.';	
	aLangKeys['es']['aboutus7']='What do ';	
	aLangKeys['es']['aboutus8']='we';	
	aLangKeys['es']['aboutus9']='actually do?';	
	aLangKeys['es']['aboutus10']='Diseño Web';
	aLangKeys['es']['aboutus11']='Programación';
	aLangKeys['es']['aboutus12']='UI/UX';
	aLangKeys['es']['aboutus13']='Diversión';
	aLangKeys['es']['aboutus14']='Nuestra ';
	aLangKeys['es']['aboutus15']='Estrategia';
	aLangKeys['es']['aboutus16']='Responsabilidad';	
	aLangKeys['es']['aboutus17']='Nosotros sólo trabajamos con desarrolladores muy responsables, que le darán lo mejor de si para lograr los mejores resultados posibles.';
	aLangKeys['es']['aboutus18']='Trabajo en Equipo';
	aLangKeys['es']['aboutus19']='We have co-located teams that will work together in your project. Communication is one of the keys of success in Agile projects, so we need highly comunnicated teams, with very good soft skills.';
	aLangKeys['es']['aboutus20']='Innovación';
	aLangKeys['es']['aboutus21']='We know that each application can be improved. We work with you not only to develop your application, but to give some ideas about how your application could be better. We want your success, because that is our success.';
	aLangKeys['es']['aboutus22']='FanLabs ';
	aLangKeys['es']['aboutus23']='en Números';
	aLangKeys['es']['aboutus24']='Tazas de Café';
	aLangKeys['es']['aboutus25']='Termos de Mate';
	aLangKeys['es']['aboutus26']='Cervezas';
	aLangKeys['es']['aboutus27']='Ajedrez';
	aLangKeys['es']['serviceTitle1']='Desarrollo';
	aLangKeys['es']['serviceTitle2']='Aplicaciones Web';
	aLangKeys['es']['serviceTitle3']='Diseños Modernos';
	aLangKeys['es']['serviceTitle4']='Código Elegante';
	aLangKeys['es']['serviceTitle5']='Personalizado';
	aLangKeys['es']['serviceTitle6']='Ideas Creativas';
	aLangKeys['es']['service1']='Somos un equipo fuerte y experimentado, capaz de desarrollar cualquier aplicación empleando las tecnologías más avanzadas.';
	aLangKeys['es']['service2']='Diseñamos y desarrollamos aplicaciones web de forma personalizadas tal como nuestros clientes lo desean.';
	aLangKeys['es']['service3']='Utilizamos técnicas de diseño web modernas para construir un único sitio web que se adapte a múltiples resoluciones de pantalla.';
	aLangKeys['es']['service4']='Trabajamos en busca de la más alta calidad y rendimiento en todos nuestros desarrollos.';
	aLangKeys['es']['service5']='Trabajamos con usted para explorar nuevas ideas, productos y servicios diseñados con amor y experiencias de usuario encantadoras.';
	aLangKeys['es']['service6']='Trabajamos con usted no sólo para desarrollar su aplicación, sino para aportar algunas ideas acerca de cómo su aplicación podría ser mejor.';
	aLangKeys['es']['service7']='nuestros ';
	aLangKeys['es']['service8']='Servicios';	
	aLangKeys['es']['service9']='En FanLabs queremos ofrecer a nuestros clientes ';
	aLangKeys['es']['service10']='todos los servicios de forma eficiente';
	aLangKeys['es']['service11']=' para su empresa.';
	aLangKeys['es']['service12']='Envíanos tu correo electrónico y nosotros nos';
	aLangKeys['es']['service13']=' contacteremos contigo.';
	aLangKeys['es']['service14']='Únetenos!';
	aLangKeys['es']['service15']='Enviar';
	aLangKeys['es']['contactus1']='Adelante,';
	aLangKeys['es']['contactus2']=' contactános!!';
	aLangKeys['es']['contactus3']='Leer Más';
	aLangKeys['es']['team1']='Nuestro ';
	aLangKeys['es']['team2']='Equipo';
	aLangKeys['es']['team3']='Somos un ';
	aLangKeys['es']['team4']='equipo';
	aLangKeys['es']['team5']=' que ';
	aLangKeys['es']['team6']='amamos';
	aLangKeys['es']['team7']=' lo que hacemos!. Contamos con diferentes habilidades y fusionamos estas habilidades para ';
	aLangKeys['es']['team8']='crear';
	aLangKeys['es']['team9']=' un software ';
	aLangKeys['es']['team10']='robusto, dinámico and amigable.';
	aLangKeys['es']['team11']='Nosotros ';
	aLangKeys['es']['team12']='somos el ';
	aLangKeys['es']['team13']='equipo';
	aLangKeys['es']['team14']='Perfil Completo';
	aLangKeys['es']['team15']='Co-Fundador & Programador';

    $('.lang').click( function() {
        var lang = $(this).attr('id'); // obtain language id
        // translate all translatable elements
        $('.translate').each(function(i){
          $(this).text(aLangKeys[lang][ $(this).attr('key') ]);
        });
    } );
});
